# Generated by Django 4.1 on 2022-10-02 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creation_date', models.DateTimeField(auto_now_add=True)),
                ('Announcement_title', models.CharField(max_length=255)),
                ('Announcement_text', models.TextField(default='content')),
                ('Category', models.CharField(choices=[('Tank', 'Танки'), ('Heal', 'Хилы'), ('DD', 'ДД'), ('Sales', 'Торговецы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('BS', 'Кузнецы'), ('PS', 'Кожевники'), ('Potions', 'Зельевары'), ('Magic', 'Мастера заклинаний')], max_length=300)),
                ('Announcement_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='file-name', max_length=255)),
                ('File', models.FileField(blank=True, null=True, upload_to='')),
                ('File_type', models.TextField(default='jpg')),
                ('Announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(default='comment')),
                ('Comment_date', models.DateTimeField(auto_now_add=True)),
                ('Comment_accepted', models.BooleanField(default=False)),
                ('Announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.announcement')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
