# Generated by Django 4.1 on 2022-10-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_onetimecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='Code',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
