# Generated by Django 4.1 on 2022-10-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_onetimecode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='Code',
            field=models.CharField(default='', max_length=4),
        ),
    ]
