# Generated by Django 4.1 on 2022-11-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
