# Generated by Django 4.1 on 2022-12-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
